name: tutorbot-local
services:
  redis:
    command:
      - redis-server
      - --appendonly
      - "yes"
    container_name: redis
    image: redis:7-alpine
    networks:
      app-net: null
    ports:
      - mode: ingress
        target: 6379
        published: "6379"
        protocol: tcp
    volumes:
      - type: volume
        source: redis-data
        target: /data
        volume: {}
networks:
  app-net:
    name: tutorbot-local_app-net
    driver: bridge
volumes:
  redis-data:
    name: tutorbot-local_redis-data

