version: "3.9"

name: tutorbot-railway-ref

# Archivo de referencia para Railway:
# - backend       -> http://backend:8000
# - rasa          -> http://rasa:5005
# - action-server -> http://action-server:5055
# - admin         -> http://admin:80
# Railway gestiona el tráfico público por servicio; aquí no publicamos puertos.

services:
  backend:
    image: docker.io/diego0102/zajuna-backend:${TAG:-latest}
    container_name: backend
    restart: unless-stopped
    environment:
      APP_ENV: "prod"
      DEBUG: "false"
      MONGO_URI: ${MONGO_URI}
      MONGO_DB_NAME: ${MONGO_DB_NAME:-tutor_virtual}
      RASA_URL: "http://rasa:5005"
      FRONTEND_SITE_URL: ${FRONTEND_SITE_URL}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - rasa
    networks:
      - app-net

  rasa:
    image: docker.io/diego0102/zajuna-rasa:${TAG:-latest}
    container_name: rasa
    restart: unless-stopped
    environment:
      ACTION_SERVER_URL: "http://action-server:5055/webhook"
      RASA_AUTOTRAIN: "true"
    depends_on:
      - action-server
    networks:
      - app-net

  action-server:
    image: docker.io/diego0102/zajuna-action:${TAG:-latest}
    container_name: action-server
    restart: unless-stopped
    networks:
      - app-net

  admin:
    image: docker.io/diego0102/zajuna-admin:${TAG:-latest}
    container_name: admin
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
