version: "3.9"

services:
  nginx-dev:
    image: nginx:1.25-alpine
    container_name: nginx-dev
    restart: unless-stopped
    depends_on:
      - backend-dev
      - admin-dev
      - rasa
    ports:
      - "8080:80"
    volumes:
      - ./ops/nginx/conf.d/dev.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-net

networks:
  app-net:
    external: true
