# docker-compose.nginx.yml
version: "3.9"

services:
  nginx-dev:
    image: nginx:1.25-alpine
    container_name: nginx-dev
    restart: unless-stopped
    depends_on:
      - backend-dev
      - admin-dev
      - rasa
    ports:
      - "8080:80"
    # ⬇️ Monta TODA la carpeta de conf (necesario para includes)
    volumes:
      - ./ops/nginx/conf.d:/etc/nginx/conf.d:ro
    networks:
      - app-net

networks:
  app-net:
    external: true
