version: "3.9"

services:
  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - backend
      - admin
      - rasa
    ports:
      - "80:80"
    volumes:
      - ./ops/nginx/conf.d:/etc/nginx/conf.d:ro
    networks:
      - app-net

networks:
  app-net:
    external: false
