# docker-compose.override.nginx-dev.yml
# Usar junto con el override dev:
#   docker compose -f docker-compose.yml -f docker-compose.override.dev.yml -f docker-compose.override.nginx-dev.yml up -d --build

services:
  nginx-dev:
    image: nginx:alpine
    container_name: nginx-dev
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - backend-dev
      - admin-dev
      - rasa
    # ⬇️ Importante: carpeta completa, no un default.conf suelto
    volumes:
      - ./ops/nginx/conf.d:/etc/nginx/conf.d:ro
    networks:
      - app-net
