version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    command: ["redis-server","--appendonly","yes"]
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-net

  # ---- Override para PROD (servicio: backend) ----
  backend:
    environment:
      RATE_LIMIT_BACKEND: redis
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis
    networks:
      - app-net

  # ---- Override para DEV (servicio: backend-dev) ----
  backend-dev:
    environment:
      RATE_LIMIT_BACKEND: redis
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis
    networks:
      - app-net

volumes:
  redis-data:

networks:
  app-net:
    external: true
