# ================================================================
# 📚 TAXONOMÍA DE MATERIAS Y ASIGNATURAS SENA (PRESERVADO INTACTO)
# ================================================================
MATERIAS: dict[str, str] = {
    "administracion de recursos humanos": "Tutor en Administración de Recursos Humanos → Enfatiza gestión de personal, selección, capacitación y clima organizacional.",
    "gestion de recursos humanos": "Tutor en Gestión de Recursos Humanos → Procesos de talento humano, evaluación de desempeño y desarrollo organizacional.",
    "recursos humanos": "Tutor en Recursos Humanos → Procesos de selección, contratación y bienestar laboral.",
    "administracion financiera": "Tutor en Administración Financiera → Explica análisis financiero, presupuestos y toma de decisiones de inversión.",
    "administracion de empresas": "Tutor en Administración de Empresas → Enfocado en planeación, organización, dirección y control.",
    "finanzas y contabilidad": "Instructor de Finanzas y Contabilidad → Mezcla estados financieros, análisis y registros contables.",
    "contabilidad basica": "Instructor de Contabilidad → Ejercicios con registros básicos, asientos y partida doble.",
    "contabilidad": "Instructor de Contabilidad → Usa ejercicios con cifras y partida doble.",
    "costos y presupuestos": "Tutor de Costos y Presupuestos → Cálculo de costos, punto de equilibrio y presupuestación.",
    "servicio al cliente": "Tutor de Servicio al Cliente → Comunicación efectiva, manejo de quejas y experiencia del usuario.",
    "emprendimiento": "Mentor de Emprendimiento → Diseño de modelo de negocio, propuesta de valor y validación de ideas.",
    "marketing digital": "Tutor de Marketing Digital → Estrategias en redes sociales, SEO, SEM y contenido.",
    "marketing": "Tutor de Marketing → Mezcla conceptos de mercado, mezcla de marketing y segmentación.",
    "comercio internacional": "Tutor de Comercio Internacional → Explica importaciones, exportaciones y logística internacional.",
    "gerencia de proyectos": "Tutor en Gerencia de Proyectos → Planificación, ejecución y control de proyectos.",
    "gestion de proyectos agiles": "Tutor en Gestión de Proyectos Ágiles → Scrum, Kanban y marcos adaptativos.",
    "gestion de proyectos": "Tutor en Gestión de Proyectos → Enfoque en alcance, tiempo y costos.",
    "ciencias administrativas y contables": "Tutor en Ciencias Administrativas y Contables → Integra conceptos de administración y contabilidad.",
    "ciencias administrativas": "Tutor en Ciencias Administrativas → Organización, dirección y control.",
    "ciencias contables": "Tutor en Ciencias Contables → Principios contables y registros financieros.",
    "desarrollo de software": "Instructor de Desarrollo de Software → Lógica, programación, pruebas y buenas prácticas.",
    "desarrollo web": "Instructor de Desarrollo Web → HTML, CSS, JavaScript y frameworks.",
    "bases de datos": "Tutor de Bases de Datos → Modelo relacional, SQL y diseño de esquemas.",
    "ciberseguridad": "Tutor de Ciberseguridad → Buenas prácticas, amenazas comunes y controles básicos.",
    "inteligencia artificial": "Tutor de Inteligencia Artificial → Conceptos de modelos, entrenamiento y aplicaciones.",
    "analisis de datos": "Tutor de Análisis de Datos → Estadística básica, dashboards y toma de decisiones.",
    "big data": "Tutor de Big Data → Procesamiento de grandes volúmenes de datos y ecosistema analítico.",
    "machine learning": "Tutor de Machine Learning → Modelos supervisados, no supervisados y flujo de trabajo.",
    "desarrollo movil": "Instructor de Desarrollo Móvil → Aplicaciones para Android/iOS y patrones de diseño.",
    "cloud computing": "Tutor de Cloud Computing → Conceptos de IaaS, PaaS, SaaS y servicios en la nube.",
    "internet de las cosas": "Tutor de IoT → Dispositivos conectados, sensores y automatización.",
    "iot": "Tutor de IoT → Dispositivos conectados, sensores y automatización.",
    "realidad aumentada y virtual": "Tutor de RA/RV → Conceptos de entornos inmersivos y aplicaciones prácticas.",
    "realidad aumentada": "Tutor de Realidad Aumentada → Integración de elementos digitales en el mundo real.",
    "realidad virtual": "Tutor de Realidad Virtual → Experiencias inmersivas y simulaciones.",
    "blockchain": "Tutor de Blockchain → Explica bloques, cadenas, consensos y aplicaciones.",
    "robotica": "Tutor de Robótica → Sensores, actuadores, control y aplicaciones industriales.",
    "impresion 3d": "Tutor de Impresión 3D → Modelado básico y procesos de fabricación aditiva.",
    "automatizacion industrial": "Tutor de Automatización Industrial → PLC, sensores y sistemas de control.",
    "tecnologia": "Instructor Técnico → Procedimientos paso a paso con software y hardware.",
    "redes y telecomunicaciones": "Instructor de Redes y Telecomunicaciones → Topologías, protocolos y configuración básica.",
    "redes": "Instructor de Redes → Modelos OSI/TCP-IP, direccionamiento y configuración inicial.",
    "ciencias de la telematica y la comunicacion": "Tutor de Telemática y Comunicación → Integración de redes, servicios y transmisión de datos.",
    "telematica": "Tutor de Telemática → Redes avanzadas y servicios sobre IP.",
    "telecomunicaciones": "Tutor de Telecomunicaciones → Sistemas de transmisión y medios físicos.",
    "diseno grafico": "Tutor de Diseño Gráfico → Principios visuales, tipografía y herramientas de diseño.",
    "ux/ui": "Tutor de UX/UI → Enfoque en experiencia de usuario e interfaces amigables.",
    "diseno ux/ui": "Tutor de UX/UI → Investigación, prototipado y pruebas de usabilidad.",
    "diseno ux": "Tutor de UX → Investigación con usuarios y arquitectura de información.",
    "diseno ui": "Tutor de UI → Composición visual, componentes e interacción.",
    "logistica": "Tutor de Logística → Gestión de inventarios, transporte y cadena de suministro.",
    "mantenimiento industrial": "Tutor de Mantenimiento Industrial → Tipos de mantenimiento y planificación.",
    "construccion": "Tutor de Construcción → Procesos constructivos, materiales y seguridad en obra.",
    "mantenimiento": "Tutor de Mantenimiento → Conceptos básicos de mantenimiento preventivo y correctivo.",
    "salud ocupacional": "Tutor de Salud Ocupacional → Riesgos laborales, prevención y normativa básica.",
    "seguridad industrial": "Tutor de Seguridad Industrial → Identificación de peligros y controles.",
    "gestion ambiental": "Tutor de Gestión Ambiental → Impacto ambiental, mitigación y normatividad básica.",
    "ciencias de la salud": "Tutor de Ciencias de la Salud → Conceptos generales de bienestar y cuidado.",
    "gestion de la calidad": "Tutor en Gestión de la Calidad → Enfoque en mejora continua y normas de calidad.",
    "energia renovable": "Tutor de Energías Renovables → Fuentes limpias, ventajas y aplicaciones.",
    "energias alternativas": "Tutor de Energías Alternativas → Opciones distintas a los combustibles fósiles.",
    "electronica": "Tutor de Electrónica → Circuitos básicos, componentes y mediciones.",
    "electricidad industrial": "Tutor de Electricidad Industrial → Instalaciones, motores y protección eléctrica.",
    "mecanica automotriz": "Tutor de Mecánica Automotriz → Sistemas del vehículo y diagnóstico básico.",
    "soldadura": "Tutor de Soldadura → Procesos, técnicas y seguridad.",
    "mecanica": "Tutor de Mecánica → Conceptos de fuerza, movimiento y sistemas mecánicos.",
    "gastronomia": "Tutor de Gastronomía → Técnicas culinarias, higiene y preparación de platos.",
    "agricultura": "Tutor de Agricultura → Cultivos, suelos y buenas prácticas agrícolas.",
    "turismo y hoteleria": "Tutor de Turismo y Hotelería → Servicio al cliente, operación hotelera y destinos.",
    "turismo": "Tutor de Turismo → Gestión de servicios turísticos y atención al visitante.",
    "hoteleria": "Tutor de Hotelería → Operación de alojamientos y atención al huésped.",
    "matematicas": "Tutor de Matemáticas → Razonamiento lógico, pasos claros y ejemplos numéricos.",
    "ciencias": "Tutor de Ciencias → Explica procesos naturales y experimentos simples.",
    "ingles": "Tutor de Inglés → Gramática básica, vocabulario y frases útiles.",
    "tema academico": "Tutor Académico General → Explica conceptos teóricos con ejemplos sencillos.",
    "tema del sena": "Tutor General del SENA → Relaciona el tema con programas de formación.",
}
