# ==========================================================
# Servidor auxiliar para pruebas exclusivas de Rasa.
#
# Utiliza el upstream global "rasa_upstream"
# definido en nginx.dev.conf.
#
# Permite acceder a:
#   http://rasa-dev.local
#
# No reemplaza el servidor principal de desarrollo.
# ==========================================================
server {
  listen 80;                
  server_name rasa-dev.local;  

  client_max_body_size 50m;
  proxy_connect_timeout 5s;
  proxy_send_timeout    86400;
  proxy_read_timeout    86400;
  send_timeout          60s;

  location = /rasa/status {
    proxy_pass http://rasa_upstream/status;
    proxy_http_version 1.1;

    proxy_set_header   Host $host;
    proxy_set_header   X-Real-IP $remote_addr;
    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header   X-Forwarded-Proto $scheme;

    add_header Access-Control-Allow-Origin "*" always;
  }


  location /rasa/ {
    proxy_pass http://rasa_upstream/;
    proxy_http_version 1.1;

    proxy_set_header   Host $host;
    proxy_set_header   X-Real-IP $remote_addr;
    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header   X-Forwarded-Proto $scheme;
    proxy_buffering    off;

    proxy_set_header   Upgrade $http_upgrade;
    proxy_set_header   Connection "upgrade";

    add_header Access-Control-Allow-Origin  * always;
    add_header Access-Control-Allow-Methods "GET, POST, OPTIONS" always;
    add_header Access-Control-Allow-Headers "Authorization, Content-Type" always;

    if ($request_method = OPTIONS) { return 204; }
  }

  location /ws/ {
    proxy_pass http://rasa_upstream/ws/;
    proxy_http_version 1.1;

    proxy_set_header   Upgrade $http_upgrade;
    proxy_set_header   Connection $connection_upgrade;

    proxy_set_header   Host $host;
    proxy_set_header   X-Real-IP $remote_addr;
    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header   X-Forwarded-Proto $scheme;

    proxy_read_timeout 86400;
    proxy_send_timeout 86400;
  }
}
