# ==========================================================
# 🌐 SERVIDOR HTTPS PRINCIPAL
# ==========================================================
server {
  listen 443 ssl;
  # http2 on;
  server_name _;

  error_page 497 https://localhost$request_uri;
  ssl_certificate     /etc/nginx/certs/fullchain.pem;
  ssl_certificate_key /etc/nginx/certs/privkey.pem;

  # 🔒 Parámetros TLS endurecidos
  include /etc/nginx/conf.d/prod/tls_params.conf;

  # Raíz SPA (mismo que default.conf)
  root  /usr/share/nginx/html;
  index index.html;
  location / {
      try_files $uri $uri/ /index.html;
  }
  # Inyectamos TODOS los locations comunes
  include /etc/nginx/conf.d/common/includes/locations.inc;
}