upstream backend_upstream {
    server backend:8000;
    keepalive 32;
}

upstream admin_up {
    server admin:80;
    keepalive 32;
}

upstream rasa_upstream {
    server rasa:5005;
    keepalive 16;
}