name: Smoke Tests

on:
  push:
    branches: [ "master", "main" ]
  pull_request:

jobs:
  smoke:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6
        ports: [ "27017:27017" ]
      redis:
        image: redis:7-alpine
        ports: [ "6379:6379" ]

    env:
      PROXY_BASE: "http://nginx-dev"
      BACKEND: "http://backend-dev:8000"
      RASA: "http://rasa:5005"
      PYTEST_PATH: "test"
      PYTEST_HTML: "reports/smoke.html"
      PYTHONUTF8: "1"
      PYTHONIOENCODING: "utf-8"
      COMPOSE_PROJECT_NAME: "tutorbot-local"     # <- clave para que la red sea tutorbot-local_app-net

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create external-like network (if absent)
        run: |
          docker network ls --format '{{.Name}}' | grep -q '^tutorbot-local_app-net$' || \
          docker network create tutorbot-local_app-net

      - name: Start stack (dev)
        run: |
          docker compose -p tutorbot-local up -d mongo redis action-server rasa backend-dev admin-dev nginx-dev
          docker compose -p tutorbot-local ps

      - name: Wait for services
        run: |
          python - <<'PY'
          import time,requests,sys
          urls=[
            "http://localhost:8000/health",
            "http://localhost:5005/status",
            "http://localhost:8080/api/health"
          ]
          for i in range(90):
              ok=0
              for u in urls:
                  try:
                      r=requests.get(u,timeout=3)
                      if r.status_code==200: ok+=1
                  except Exception:
                      pass
              if ok==len(urls):
                  print("All services ready"); sys.exit(0)
              time.sleep(2)
          print("Timeout waiting services"); sys.exit(1)
          PY
        shell: bash

      - name: Run tester (pytest with HTML)
        run: |
          docker compose -p tutorbot-local -f docker-compose.tester.yml run --rm tester

      - name: Upload smoke report
        uses: actions/upload-artifact@v4
        with:
          name: smoke-report
          path: reports/smoke.html
