name: Admin CI (build + tests)

on:
  push:
    branches: [ "main" ]
    paths:
      - "admin_panel_react/**"
      - ".github/workflows/test.yml"
  pull_request:
    paths:
      - "admin_panel_react/**"
      - ".github/workflows/test.yml"
  workflow_dispatch:

jobs:
  admin-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: admin_panel_react
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: admin_panel_react/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Build (si aplica)
        run: npm run build --if-present

      - name: Unit tests (si existen)
        run: npm test --if-present -- --ci --reporter=default
